openapi: "3.0.0"
info:
  title: auth restful api documentation
  description: This is an user authentication api using nodejs and express mainly
  version: 0.1.9
  contact:
    email: kentin@intside.com
  license:
    name: apach 2.0
    url: http://apache.org
servers:
  - url: http://127.0.0.1:8080/auth/api/
    description: local server
  - url: www.company.com/auth/api/
    description: company server
schemes: [http, https]

paths:
  tags:
    "user authentication"
#user sign up documentation
  /user-sign-up:
    post:
      summary: Creates a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: Created
#user sign up documentation
  /user-sign-in:
    post:
      summary: Creates a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: sign in
#send user password resseting mail documentation
  /user-reset-pass:
    post:
      summary: send users password reset email.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        "201":
          description: email sent
#users password reset documentation
  /user-password-update:
      put:
        summary: send users password reset email.
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                  password:
                    type: string
        responses:
          "201":
            description: password reset